### ISSUE TITLE
Put your project in the EnTT in Action list

### ISSUE THREAD

**Issue by skypjack** [Trisslotten/Stort-Spelprojekt#2]
Hi, sorry to bother you, I'm the author of `EnTT`.

I found your project and I think it's very interesting in many ways. Probably you already know that but I'm also trying to give the users of `EnTT` a few examples from which to take inspiration when they move their first steps.

Since I usually prefer to ask before referring to other projects, here I am.
What do you think about putting your repo in [the list of projects](https://github.com/skypjack/entt/wiki/EnTT-in-Action) _made with `EnTT`_?
You can make a PR or just close the issue with a :+1: if you prefer, I'll add it for you.

Thanks anyway. :+1:

**Comment by Trisslotten** [comment]
:+1:
